name: asklepios_icons
description: "Asklepios icons is from strange icons asklepios icon pack with over 500 regular icons in solid and monotone styles."
version: 0.0.1
homepage: https://github.com/CoderNamedHendrick/strange_icons/tree/main/asklepios_icons
repository: https://github.com/CoderNamedHendrick/strange_icons/tree/main/asklepios_icons
topics:
  - icon-packs
  - icons
  - asklepios-icons
  - strange-icons

screenshots:
  - description: 'rendered icons example'
    path: ss/img.png

environment:
  sdk: '>=3.0.0 <4.0.0'
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0


flutter:

  fonts:
    - family: asklepios_monotone
      fonts:
        - asset: fonts/asklepios_monotone.ttf

    - family: asklepios_solid_icons
      fonts:
        - asset: fonts/asklepios_solid_icons.ttf