name: nightingale_icons
description: "Nightingale icons is from Strange icons Sandow icon pack with over 500 regular icons in monotone and solid styles."
version: 0.0.2
homepage: https://github.com/CoderNamedHendrick/strange_icons/tree/main/nightingale_icons
repository: https://github.com/CoderNamedHendrick/strange_icons/tree/main/nightingale_icons

topics:
  - icon-packs
  - icons
  - nightingale-icons
  - strange-icons

screenshots:
  - description: 'rendered icons example'
    path: ss/img.png

environment:
  sdk: '>=3.0.0 <4.0.0'
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0


flutter:
  fonts:
    - family: nightingale_solid
      fonts:
        - asset: fonts/nightingale_solid.ttf

    - family: nightingale_monotone
      fonts:
        - asset: fonts/nightingale_monotone.ttf